name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Backend CI Job - Test Backend
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Run TypeScript check
      run: |
        cd backend
        npm run type-check
    
    - name: Run linting
      run: |
        cd backend
        npm run lint
    
    - name: Run backend tests
      run: |
        cd backend
        npm run test
    
    - name: Run security audit
      run: |
        cd backend
        npm audit --audit-level moderate
    
    - name: Build backend
      run: |
        cd backend
        npm run build

  # Frontend (No tests, just build verification)
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build frontend (verification only)
      run: |
        cd frontend
        npm run build

  # Success notification
  success:
    needs: [test-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: All checks passed
      run: |
        echo "✅ Backend tests passed"
        echo "✅ Frontend builds successfully"
        echo "🚀 Ready for deployment"
